export const EDIT_NOTE = 'EDIT_NOTE'
export const NEW_NOTE = 'NEW_NOTE'
export const OPEN_NOTE = 'OPEN_NOTE'
export const OPEN_NEXT_NOTE = 'OPEN_NEXT_NOTE'
export const OPEN_PREVIOUS_NOTE = 'OPEN_PREVIOUS_NOTE'

export const COMMAND_INPUT_KEY_UP = 'COMMAND_INPUT_KEY_UP'
export const COMMAND_INPUT_CHANGE = 'COMMAND_INPUT_CHANGE'
export const TOGGLE_MODE = 'TOGGLE_MODE'
